In [1]:
import queue
import random
import numpy as np
import tensorflow as tf
from tensorflow import keras
import gym
# prints a random value from the list


In [24]:
!pip install --user pygame

In [2]:
nb_action=4

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [14]:
from  tensorflow.keras import layers

def build_model():
    model = keras.Sequential()
    # Ajouter des couches au modèle
    model.add(layers.Dense(50,input_shape=(1,nb_action,), activation="relu"))
    model.add(layers.Dense(20, activation="relu"))
    model.add(layers.Dense(50, activation="relu"))
    model.add(layers.Dense(nb_action, activation="softmax"))
    model.add(layers.Flatten())
    return model
# Compiler le modèle


In [15]:
model=build_model()

In [4]:
class Snake:
    
    

    def __init__(self):
        
        self.nb_action=4
        self.grid_size={"x":10,"y":10}
        self.grid=np.array([[0]*self.grid_size.get("y")]*self.grid_size.get("x")) #0=empty,1=body,2=head,3=cherry
        
        self.cherry_pos={"x":random.randrange(self.grid_size.get("x")-1),"y":random.randrange(self.grid_size.get("y")-1)}
        self.grid[self.cherry_pos.get("y"),self.cherry_pos.get("x")]=3
        print("self.cherry_pos: "+str(self.cherry_pos))
        self.nb_inputs=self.grid_size.get("x")*self.grid_size.get("y")
        self.new_head_pos={"x":0,"y":0}
        self.list_body_pos=[{"x":random.randrange(self.grid_size.get("x")-1),"y":random.randrange(self.grid_size.get("y")-1)},]
        #self.list_body_pos=[{"x":9,"y":9},{"x":0,"y":0}]
        print("self.list_body_pos: "+str(self.list_body_pos))
        self.grid[self.list_body_pos[0].get("y"),self.list_body_pos[0].get("x")]=2
        
        self.cherry_pos={"x":0,"y":0}



    def move(self,direction):
        print("self.new_head_pos: "+str(self.new_head_pos))
        self.new_head_pos["x"]=self.list_body_pos[0].get("x")
        self.new_head_pos["y"]=self.list_body_pos[0].get("y")
        if direction==0:
            self.new_head_pos["x"]=self.list_body_pos[0].get("x")+1
        if direction==1:
            self.new_head_pos["y"]=self.list_body_pos[0].get("y")-1
        if direction==2:
            self.new_head_pos["x"]=self.list_body_pos[0].get("x")-1
        if direction==3:
            self.new_head_pos["y"]=self.list_body_pos[0].get("y")+1
        self.react()




    def react(self):
        print("self.new_head_pos: "+str(self.new_head_pos))
        print("self.list_body_pos: "+str(self.list_body_pos))
        if self.new_head_pos.get("y")<0:
            print("fail")
            return 0
        if self.new_head_pos.get("x")<0:
            print("fail")
            return 0
        if self.new_head_pos.get("y")>=self.grid_size.get("y"):
            print("fail")
            return 0
        if self.new_head_pos.get("x")>=self.grid_size.get("x"):
            print("fail")
            return 0
        if self.new_head_pos in self.list_body_pos:
            print("fail")
            return 0
        self.list_body_pos.insert(0,{"x":self.new_head_pos.get("x"),"y":self.new_head_pos.get("y")})#advance
        

        self.grid[self.list_body_pos[1].get("y"),self.list_body_pos[1].get("x")]=1
        print("self.new_head_pos: "+str(self.new_head_pos))
        print("self.cherry_pos: "+str(self.cherry_pos))
        if False:#self.new_head_pos!=self.cherry_pos:
            print("pas cherry")
            print("self.list_body_pos[-1]: "+str(self.list_body_pos[-1]))
            popped=self.list_body_pos.pop(-1)                       #remove tail
            self.grid[popped.get("y"),popped.get("x")]=0  
            
        else:
            print("cherry")
            if len(self.list_body_pos) >= 10:
                print("win")
                return 1
            self.cherry_pos["x"]=random.randrange(self.grid_size.get("x")-1)
            i=0
            while i < 999:
                i+=1
                self.cherry_pos["x"]=random.randrange(self.grid_size.get("x")-1) #new postion for cherry
                self.cherry_pos["y"]=random.randrange(self.grid_size.get("y")-1)
                if self.cherry_pos not in self.list_body_pos:
                    self.grid[self.cherry_pos.get("y"),self.cherry_pos.get("x")]=3
                    break
                    
                    
        self.grid[self.new_head_pos.get("y"),self.new_head_pos.get("x")]=2
            #ask_input(grid.flatten())


In [138]:
snake=Snake()

print(snake.grid)

self.cherry_pos: {'x': 5, 'y': 0}
self.list_body_pos: [{'x': 4, 'y': 3}]
[[0 0 0 0 0 3 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


  Created wheel for keras-rl: filename=keras_rl-0.4.2-cp37-none-any.whl size=48385 sha256=dfa302e0c62f13a3d64450c96f5b3e78f842ab915b895faf6bbb6937affdb4a6
  Stored in directory: C:\Users\philg\AppData\Local\pip\Cache\wheels\7d\4d\84\9254c9f2e8f51865cb0dac8e79da85330c735551d31f73c894
Successfully built keras-rl


In [149]:
print(snake.grid)
ans=int(input("Entrez coup: "))
snake.move(ans)
print(snake.grid)

[[3 3 0 0 3 3 0 3 0 0]
 [0 3 3 3 3 0 3 3 3 0]
 [0 0 3 3 3 3 3 3 3 0]
 [3 3 3 0 1 1 1 1 1 1]
 [0 0 3 3 0 0 3 0 3 1]
 [0 3 0 0 0 3 3 3 3 1]
 [3 3 3 3 0 0 0 3 3 1]
 [0 3 3 0 3 0 3 3 0 1]
 [3 3 3 3 0 3 3 3 0 2]
 [0 0 0 0 0 0 0 0 0 0]]
Entrez coup: 3
self.new_head_pos: {'x': 9, 'y': 8}
self.new_head_pos: {'x': 9, 'y': 9}
self.list_body_pos: [{'x': 9, 'y': 8}, {'x': 9, 'y': 7}, {'x': 9, 'y': 6}, {'x': 9, 'y': 5}, {'x': 9, 'y': 4}, {'x': 9, 'y': 3}, {'x': 8, 'y': 3}, {'x': 7, 'y': 3}, {'x': 6, 'y': 3}, {'x': 5, 'y': 3}, {'x': 4, 'y': 3}]
self.new_head_pos: {'x': 9, 'y': 9}
self.cherry_pos: {'x': 2, 'y': 2}
cherry
0
test
1
test
test
2
test
3
test
4
test
5
test
6
test
7
test
8
test
9
test
test
[[3 3 3 0 3 3 0 3 3 0]
 [0 3 3 3 3 3 3 3 3 0]
 [0 0 3 3 3 3 3 3 3 0]
 [3 3 3 0 1 1 1 1 1 1]
 [0 0 3 3 0 0 3 0 3 1]
 [0 3 0 0 3 3 3 3 3 1]
 [3 3 3 3 0 3 0 3 3 1]
 [0 3 3 0 3 0 3 3 0 1]
 [3 3 3 3 0 3 3 3 0 1]
 [0 0 0 0 0 0 0 0 0 2]]


In [18]:
class GridWorldEnv(gym.Env):
    

    def __init__(self):
        
        self.nb_action=4
        self.grid_size={"x":10,"y":10}


    def step(self,direction):
        print("self.new_head_pos: "+str(self.new_head_pos))
        self.new_head_pos["x"]=self.list_body_pos[0].get("x")
        self.new_head_pos["y"]=self.list_body_pos[0].get("y")
        if direction==0:
            self.new_head_pos["x"]=self.list_body_pos[0].get("x")+1
        if direction==1:
            self.new_head_pos["y"]=self.list_body_pos[0].get("y")-1
        if direction==2:
            self.new_head_pos["x"]=self.list_body_pos[0].get("x")-1
        if direction==3:
            self.new_head_pos["y"]=self.list_body_pos[0].get("y")+1
        return self.react()




    def react(self):
        done=False
        reward=0
        print("self.new_head_pos: "+str(self.new_head_pos))
        print("self.list_body_pos: "+str(self.list_body_pos))
        if self.new_head_pos.get("y")<0:
            print("fail")
            done = True
        if self.new_head_pos.get("x")<0:
            print("fail")
            done = True
        if self.new_head_pos.get("y")>=self.grid_size.get("y"):
            print("fail")
            done = True
        if self.new_head_pos.get("x")>=self.grid_size.get("x"):
            print("fail")
            done = True
        if self.new_head_pos in self.list_body_pos:
            print("fail")
            done = True
        self.list_body_pos.insert(0,{"x":self.new_head_pos.get("x"),"y":self.new_head_pos.get("y")})#advance
        

        self.grid[self.list_body_pos[1].get("y"),self.list_body_pos[1].get("x")]=1
        print("self.new_head_pos: "+str(self.new_head_pos))
        print("self.cherry_pos: "+str(self.cherry_pos))
        if elf.new_head_pos!=self.cherry_pos:
            print("pas cherry")
            print("self.list_body_pos[-1]: "+str(self.list_body_pos[-1]))
            popped=self.list_body_pos.pop(-1)                       #remove tail
            self.grid[popped.get("y"),popped.get("x")]=0  
            
        else:
            print("cherry")
            reward=1
            if len(self.list_body_pos) >= 10:
                print("win")
                done=True
            self.cherry_pos["x"]=random.randrange(self.grid_size.get("x")-1)
            i=0
            while i < 999:
                i+=1
                self.cherry_pos["x"]=random.randrange(self.grid_size.get("x")-1) #new postion for cherry
                self.cherry_pos["y"]=random.randrange(self.grid_size.get("y")-1)
                if self.cherry_pos not in self.list_body_pos:
                    self.grid[self.cherry_pos.get("y"),self.cherry_pos.get("x")]=3
                    break
                               
        self.grid[self.new_head_pos.get("y"),self.new_head_pos.get("x")]=2
        
        observation = self._get_obs()
        info = self._get_info()
        return observation, reward, done, info
        
    def _get_obs(self):
            return self.grid.flatten()
        
    def _get_info(self):
        return {}
            
    def reset(self, seed=None, return_info=False, options=None):
        self.grid=np.array([[0]*self.grid_size.get("y")]*self.grid_size.get("x")) #0=empty,1=body,2=head,3=cherry  
        self.cherry_pos={"x":random.randrange(self.grid_size.get("x")-1),"y":random.randrange(self.grid_size.get("y")-1)}
        self.grid[self.cherry_pos.get("y"),self.cherry_pos.get("x")]=3
        print("self.cherry_pos: "+str(self.cherry_pos))
        self.nb_inputs=self.grid_size.get("x")*self.grid_size.get("y")
        self.new_head_pos={"x":0,"y":0}
        self.list_body_pos=[{"x":random.randrange(self.grid_size.get("x")-1),"y":random.randrange(self.grid_size.get("y")-1)},]
        print("self.list_body_pos: "+str(self.list_body_pos))
        self.grid[self.list_body_pos[0].get("y"),self.list_body_pos[0].get("x")]=2
        self.cherry_pos={"x":0,"y":0}
            
            
        observation = self._get_obs()
        info = self._get_info()

        return (observation, info) if return_info else observation
        
     

In [19]:
env = GridWorldEnv()

In [20]:

from rl.agents import DQNAgent
from rl.policy import BoltzmannQPolicy
from rl.memory import SequentialMemory


In [21]:
def build_agent(model, actions):
    policy = BoltzmannQPolicy()
    memory = SequentialMemory(limit=50000, window_length=1)
    dqn = DQNAgent(model=model, memory=memory, policy=policy, 
                  nb_actions=4, nb_steps_warmup=10, target_model_update=1e-2)
    return dqn



In [22]:


dqn = build_agent(model, 4)
dqn.compile(Adam(lr=1e-3), metrics=['mae'])
dqn.fit(env, nb_steps=50000, visualize=False, verbose=1)



TypeError: Keras symbolic inputs/outputs do not implement `__len__`. You may be trying to pass Keras symbolic inputs/outputs to a TF API that does not register dispatching, preventing Keras from automatically converting the API call to a lambda layer in the Functional Model. This error will also get raised if you try asserting a symbolic input/output directly.

In [ ]:
scores = dqn.test(env, nb_episodes=100, visualize=False)
print(np.mean(scores.history['episode_reward']))

TypeError: Keras symbolic inputs/outputs do not implement `__len__`. You may be trying to pass Keras symbolic inputs/outputs to a TF API that does not register dispatching, preventing Keras from automatically converting the API call to a lambda layer in the Functional Model. This error will also get raised if you try asserting a symbolic input/output directly.